run:
  timeout: 5m
  go: "1.23"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - exhaustive
    - noctx
    - bodyclose
    - exportloopref

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: noto
  revive:
    rules:
      - name: exported
        severity: warning
      - name: var-naming
        severity: warning
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
  max-issues-per-linter: 0
  max-same-issues: 0
